
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2MjllMzEwLWFmOTMtNGU3Yy04MjVhLTBmMDgyYzdmY2RhZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1Nzg5OTcxMn0.tZ5eX8No3IXZBHDwj-FKzksZSObJylXEXEnXWIkZ7zs

POST http://localhost:3003/user/signUp
Content-Type: application/json

{
    "name":"Matheus",
    "email":"matheus@gmail.com",
    "password":"12345678",
    "role":"ADMIN"
}


###

POST http://localhost:3003/user/login
Content-Type: application/json

{

    "email": "matheus@gmail.com",
    "password":"12345678"

}

### 

POST http://localhost:3003/band/adicionar
Authorization: {{token}}
Content-Type: application/json

{
     "name": "Anitta e sua banda",
     "music_genre": "Pop/Funk",
     "responsible": "Anitta"
}

###

GET http://localhost:3003/band/9bd4adbf-aa46-4730-ad7b-16ad564061d2
Authorization: {{token}}